import './styles.css';
import gif from './img/test.gif';
const ele = document.getElementById("test");
const ele1 = document.getElementById("test1");
const ele2 = document.getElementById("test2");
const ele3 = document.getElementById("test3");
const ele4 = document.getElementById("test4");
const ele5 = document.getElementById("test5");
const ele6 = document.getElementById("test6");
const ele7 = document.getElementById("test7");
const ele8 = document.getElementById("test8");
const ele9 = document.getElementById("test9");
const ele10 = document.getElementById("test10");
const ele11 = document.getElementById("test11");
const ele12 = document.getElementById("test12");
const ele13 = document.getElementById("test13");
const ele14 = document.getElementById("test14");
const ele15 = document.getElementById("test15");
const ele16 = document.getElementById("test16");
const ele17 = document.getElementById("test17");
const ele18 = document.getElementById("test18");
const ele19 = document.getElementById("test19");
const ele20 = document.getElementById("test20");
const ele21 = document.getElementById("test21");
const ele22 = document.getElementById("test22");
const ele23 = document.getElementById("test23");
const ele24 = document.getElementById("test24");
const ele25 = document.getElementById("test25");
import pd from './ResumeSeptember2019.pdf';
const elep = document.getElementById('resume');
elep.href = pd;
ele.src = gif;
ele1.src = gif;
ele2.src = gif;
ele3.src = gif;
ele4.src = gif;
ele5.src = gif;
ele6.src = gif;
ele7.src = gif;
ele8.src = gif;
ele9.src = gif;
ele10.src = gif;
ele11.src = gif;
ele12.src = gif;
ele13.src = gif;
ele14.src = gif;
ele15.src = gif;
ele16.src = gif;
ele17.src = gif;
ele18.src = gif;
ele19.src = gif;
ele20.src = gif;
ele21.src = gif;
ele22.src = gif;
ele23.src = gif;
ele24.src = gif;
ele25.src = gif;
$(document).ready(function(){
});

$(window).on("scroll", function() {
    var scrollTop = $(window).scrollTop();
    var oddImgPos = scrollTop / 3 + 'px';
    var evenImgPos = (scrollTop/5) / 2.5 + 'px';
    var p = $( "#p2" ).first();
    var position = p.position();
    //all end at 255
    // $( "#p1" ).first().position().top;
    // $( "#p2" ).first().position().top;
    // $( "#p3" ).first().position().top;
    // $( "#p4" ).first().position().top;
    // $( "#p5" ).first().position().top;
    // $( "#p6" ).first().position().top;
    // $( "#p7" ).first().position().top;
    // $( "#p8" ).first().position().top;
    // $( "#p9" ).first().position().top;
    // $( "#p10" ).first().position().top;
    // $( "#p11" ).first().position().top;
    // $( "#p12" ).first().position().top;
    // $( "#p13" ).first().position().top;
    // $( "#p14" ).first().position().top;
    // $( "#p15" ).first().position().top;
    // $( "#p16" ).first().position().top;
    // $( "#p17" ).first().position().top;
    // $( "#p18" ).first().position().top;
    // $( "#p19" ).first().position().top;
    // $( "#p20" ).first().position().top;
    // $( "#p21" ).first().position().top;
    // $( "#p22" ).first().position().top;
    // $( "#p23" ).first().position().top;
    // $( "#p24" ).first().position().top;
    // $( "#p25" ).first().position().top;
    // $( "#p26" ).first().position().top;
            $('.grid').find("p").css('transform', 'translateY(-' + evenImgPos + ')');
        // $('#img2').find("#p2").css('transform', 'translateY(-' + evenImgPos + ')');
    // if($('#img2').is(":visible")) {
    //     $('#img2').find("#p2").css('transform', 'translateY(-' + evenImgPos + ')');
    // }
});
